version: 2.1
jobs:
 heroku_deploy:
    steps:
      - checkout
      - build-tools/install-ci-tools
      - jq/install
    - run:
      name: Deploy
      command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/rocky-cliffs-61004.git HEAD:main

orbs:
  build-tools: circleci/build-tools@2.6.3
  jq: circleci/jq@1.9.1
workflows:
  version: 2.1
  build:
    jobs:
      - heroku_deploy
