version: '2.1'
orbs:
  heroku: circleci/heroku@2.0
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          post-steps:
            - run:
              name: Deploy
              command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/rocky-cliffs-61004.git HEAD:master
