version: 2.1
jobs:
 heroku_deploy:
    steps:
      - run:
        name: Deploy
        command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/rocky-cliffs-61004.git HEAD:main

orbs:
  heroku: circleci/heroku@2.0
workflows:
  version: 2.1
  build:
    jobs:
      - heroku_deploy
