version: '2.1'
orbs:
  heroku: circleci/heroku@2.0
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          post-steps:
            - run:
              name: Create fresh Heroku app
              command: heroku apps:create $HEROKU_APP_NAME --addons=jawsdb:kitefin --stack heroku-20
            - run:
              name: Deploy
              command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
            - run:
                name: Run post-deploy tasks
                command: |
                  heroku config:set AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_REGION=$AWS_REGION AWS_BUCKET=$AWS_BUCKET
                  heroku run bin/rails db:migrate
