version: '2.1'
orbs:
  heroku: circleci/heroku@2.0
jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
          name: Create fresh Heroku app
          command: heroku apps:create $HEROKU_APP_NAME --stack heroku-22
      - run:
          name: Create DB for Heroku app
          command: heroku addons:create jawsdb:kitefin
      - run:
          name: Deploy
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master

workflows:
  heroku_deploy:
    jobs:
      - deploy
